const LIST_REQUEST = 'LIST_REQUEST';
const LIST_REQUEST_SUCCESS = 'LIST_REQUEST_SUCCESS';
const LIST_REQUEST_FAILURE = 'LIST_REQUEST_FAILURE';

const actionsTypes = {
    LIST_REQUEST,
    LIST_REQUEST_SUCCESS,
    LIST_REQUEST_FAILURE,
};

export default actionsTypes;